/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './app/pages/@__root'
import { Route as IndexImport } from './app/pages/@index'
import { Route as WomenIndexImport } from './app/pages/@women/@index'
import { Route as MenIndexImport } from './app/pages/@men/@index'
import { Route as CustomersIndexImport } from './app/pages/@customers/@index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WomenIndexRoute = WomenIndexImport.update({
  path: '/women/',
  getParentRoute: () => rootRoute,
} as any)

const MenIndexRoute = MenIndexImport.update({
  path: '/men/',
  getParentRoute: () => rootRoute,
} as any)

const CustomersIndexRoute = CustomersIndexImport.update({
  path: '/customers/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersIndexImport
      parentRoute: typeof rootRoute
    }
    '/men/': {
      id: '/men/'
      path: '/men'
      fullPath: '/men'
      preLoaderRoute: typeof MenIndexImport
      parentRoute: typeof rootRoute
    }
    '/women/': {
      id: '/women/'
      path: '/women'
      fullPath: '/women'
      preLoaderRoute: typeof WomenIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  CustomersIndexRoute,
  MenIndexRoute,
  WomenIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "@__root.tsx",
      "children": [
        "/",
        "/customers/",
        "/men/",
        "/women/"
      ]
    },
    "/": {
      "filePath": "@index.tsx"
    },
    "/customers/": {
      "filePath": "@customers/@index.tsx"
    },
    "/men/": {
      "filePath": "@men/@index.tsx"
    },
    "/women/": {
      "filePath": "@women/@index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
